# Generated by Django 4.0.4 on 2025-02-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading Video'), ('extracting', 'Extracting Key Moments'), ('generating', 'Generating Reels'), ('completed', 'Complete'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
