# Generated by Django 4.0.4 on 2025-02-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_video_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading Video'), ('extracting', 'Extracting Key Moments'), ('generating', 'Generating Reels'), ('completed', 'Complete'), ('error', 'Error')], default='pending', max_length=100),
        ),
    ]
