# Generated by Django 4.0.4 on 2025-03-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_reel_average_rating_reelrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
