# Generated by Django 4.0.4 on 2025-03-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_reel_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allowed_videos',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='web_app.video'),
        ),
    ]
