# Generated by Django 4.0.4 on 2025-03-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_customuser_allowed_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='allowed_videos',
            field=models.ManyToManyField(blank=True, related_name='allowed_students', to='web_app.video'),
        ),
    ]
