# Generated by Django 4.0.4 on 2025-03-26 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_alter_customuser_allowed_videos'),
    ]

    operations = [
    ]
